- .gitignore
- config.py
- labconnect/__init__.py
- labconnect/forms.py
- labconnect/views.py
- requirements.txt
- run.py
Created the run, views, config, models, forms, and initialization file. These files will serve as the setup for the project.
Ran the project and tested opening the main page.
No tests yet
> Create starting flask project files

- labconnect/templates/404.html
- labconnect/templates/500.html
- labconnect/templates/base.html
- labconnect/templates/flash.html
- labconnect/templates/home.html
- labconnect/views.py
Created Jinja templates and files to start the frontend
Ran the project and navigated to different pages
No tests currently
> Setup Project Frontend

- README.md
Increase documentation on how to set up and run the project. Increased the presentability and information available on the readme.
> Update README.md to be more presentable

- .github/workflows/black.yml
- .github/workflows/isort.yml
Created new github actions to check pull request code. [Black is an uncompromising code formatter](https://github.com/psf/black) and [isort is python formatter for imports](https://pycqa.github.io/isort/).
> New github actions

- labconnect/templates/tips_and_tricks.html
Re adding the tips and trick page
> readd @sjaybush18 commit

- .github/workflows/contributors.yml
- README.md
updated README and add contributors workflow
> updated README and add contributors workflow

- labconnect/templates/base.html
- labconnect/templates/navbar.html
Small updates based on a lighthouse report.
Passed the test suite and checked the affected pages.
> Small optimizations

- Makefile
- labconnect/main/queries.py
- labconnect/main/routes.py
- tests/test_main.py
Fixed the makefile command to run coverage reports.
Ran the test suite
> Fix coverage tests

- README.md
> Update README.md to LabConnect-RCOS/LabConnect-Backend

- labconnect/main/routes.py
- tests/conftest.py
Fixes unit test for 500 error status code
Ran the pytest suite.
> Correct issue #74

- db_init.py
- labconnect/main/routes.py
- labconnect/models.py
- tests/test_main.py
Using lowercase is like functionality to match course names or course codes, and the same functionality for majors. This allows for results to appear as users input data into fields.
Used postman to test individual queries and developed 2 new unit tests for each route to test the functionality matching different columns/fields.
> Complete routes to return data with complex queries

- .github/workflows/pytest.yml
- Makefile
- README.md
> 78 update contributors list on readme

- labconnect/main/routes.py
- tests/test_main.py
fix broken test for department
Increase code coverage by testing bad input data and ensuring proper HTTP response codes.
Added more unit tests and they passed.
> Increase code coverage

- db_init.py
- labconnect/helpers.py
- labconnect/models.py
- tests/test_courses.py
- tests/test_departments.py
- tests/test_general.py
- **add cascading deleting functionality**
- **adding locations and last updated columns**
- **add new data and more example data**
- **fix unit tests with new test data**
> db updates

- db_init.py
- labconnect/__init__.py
- labconnect/main/routes.py
- labconnect/models.py
- **cleanup imports and change column name**
- **add new example data to build relationships between user and other tables**
Add new example data to test and develop routes that work with data in relationships
Ran the make create command to test the creation of data.
> connect user table

- labconnect/models.py
> serialize user table

- Dockerfile
- Explicitly set python sub version
- Explicitly set alpine version to 3.20
- Add healthcheck to Dockerfile
> Docker updates

- .github/workflows/docker-test.yml
- .github/workflows/pytest.yml
- Dockerfile
- run.sh
- **seperate start command to script**
- **new docker build test for PRs**
> New Docker test

- .github/workflows/black.yml
- .github/workflows/docker-deploy.yml
- .github/workflows/docker-test.yml
- .github/workflows/pytest.yml
- **Update checkout**
- **new docker deploy to ghcr**
> New Docker Deploy

- Dockerfile
attempt fix, can't find run.sh file
> fix run command

- .github/workflows/docker-test.yml
Improve docker run test. Runs the docker container for 1 minute to ensure it works once built
> Improve docker test

- .github/workflows/docker-test.yml
- config.py
- run.sh
- **improve docker test**
- **improve run script**
> docker test improvement

- labconnect/main/opportunity_routes.py
- labconnect/main/routes.py
- labconnect/models.py
- [X ] Bug fix (non-breaking change which fixes an issue)
> 213 fix deepsource errors

- config.py
- labconnect/__init__.py
- labconnect/main/__init__.py
- labconnect/main/auth_routes.py
- labconnect/main/discover_routes.py
- labconnect/main/opportunity_routes.py
- labconnect/main/routes.py
- labconnect/models.py
- migrations/env.py
- migrations/versions/4dd3611b273e_.py
- migrations/versions/55928fddcb12_initial_migration.py
- migrations/versions/c72f39e93d72_.py
- migrations/versions/f7518ca21f44_.py
- tests/test_opportunity.py
- **Add token blacklist set for future things**
- **update CORS to allow calls from frontend**
- **add testing branches for auth items**
Frontend changes for this PR: https://github.com/LabConnect-RCOS/LabConnect-Frontend/pull/44
> improve auth functions

- labconnect/main/auth_routes.py
Adjust token callback to new frontend route
> Callback to specific callback route on frontend

- labconnect/main/auth_routes.py
- requirements.txt
Improve the auth system by calling back to the frontend with a temp token then having the frontend request the backend with the temp token/code to retrieve the JWT
> Improve Auth System

- db_init.py
- labconnect/main/auth_routes.py
- labconnect/main/opportunity_routes.py
Added create, edit and delete routes for opportunities as well as authentication for them all.
> 223 create and edit routes

- labconnect/main/opportunity_routes.py
> 244 get and filter opportunities

- requirements.txt
Update Jinja to pactch security vulnerability
> Update Jinja to 3.1.6 for security
